//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace afdsl.DataLayer.Entity_FrameWork
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class afdsl_ModelContainer1 : DbContext
    {
        public afdsl_ModelContainer1()
            : base("name=afdsl_ModelContainer1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<cmsMember> cmsMembers { get; set; }
        public DbSet<afdsl_Custom_User_Table> afdsl_Custom_User_Table { get; set; }
        public DbSet<afdsl_Newsletter> afdsl_Newsletter { get; set; }
    }
}
