//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace afdsl.DataLayer.Entity_FrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class afdsl_Custom_User_Table
    {
        public afdsl_Custom_User_Table()
        {
            this.cmsMembers = new HashSet<cmsMember>();
            this.afdsl_Newsletter = new HashSet<afdsl_Newsletter>();
        }
    
        public int Id { get; set; }
        public bool email_SignUp { get; set; }
        public System.DateTime created_Date { get; set; }
        public System.Guid Guid { get; set; }
        public Nullable<bool> email_Confirmation { get; set; }
    
        public virtual afdsl_Custom_User_Table afdsl_Custom_User_Table1 { get; set; }
        public virtual ICollection<cmsMember> cmsMembers { get; set; }
        public virtual ICollection<afdsl_Newsletter> afdsl_Newsletter { get; set; }
    }
}
