//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace afdsl.DataLayer.Entity_FrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class afdsl_Newsletter
    {
        public int ID { get; set; }
        public string Email { get; set; }
        public Nullable<int> FK_UserTable { get; set; }
    
        public virtual afdsl_Custom_User_Table afdsl_Custom_User_Table { get; set; }
    }
}
