//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace afdsl_Web_Application.afdsl_UserControls.Hero_Gallery_Item_UserControls {
    
    
    public partial class afdsl_Hero_Gallery_Item {
        
        /// <summary>
        /// rptHeroGallery control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater rptHeroGallery;
    }
}
